name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.3'
        enable-stack: true
    - uses: actions/cache@v3
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-global-
    - uses: actions/cache@v3
      name: Cache .stack-work
      with:
        path: .stack-work
        key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml.lock') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-

    - name: Build dependencies
      run: stack build --only-dependencies --system-ghc
    - name: Build
      run: stack build --system-ghc
    - name: Run tests
      run: stack test --system-ghc
